const citiesNames = [
  { id: 1, cityName: 'Tokyo' },
  { id: 2, cityName: 'New York' },
  { id: 3, cityName: 'Paris' },
  { id: 4, cityName: 'London' },
  { id: 5, cityName: 'Bangkok' },
  { id: 6, cityName: 'Hong Kong' },
  { id: 7, cityName: 'Dubai' },
  { id: 8, cityName: 'Singapore' },
  { id: 9, cityName: 'Rome' },
  { id: 10, cityName: 'Istanbul' },
  { id: 11, cityName: 'Barcelona' },
  { id: 12, cityName: 'Amsterdam' },
  { id: 13, cityName: 'Moscow' },
  { id: 14, cityName: 'Shanghai' },
  { id: 15, cityName: 'Los Angeles' },
  { id: 16, cityName: 'Chicago' },
  { id: 17, cityName: 'Miami' },
  { id: 18, cityName: 'Madrid' },
  { id: 19, cityName: 'Berlin' },
  { id: 20, cityName: 'Vienna' },
  { id: 21, cityName: 'Melbourne' },
  { id: 22, cityName: 'Sydney' },
  { id: 23, cityName: 'Cairo' },
  { id: 24, cityName: 'Beijing' },
  { id: 25, cityName: 'Mumbai' },
  { id: 26, cityName: 'Mexico City' },
  { id: 27, cityName: 'São Paulo' },
  { id: 28, cityName: 'Buenos Aires' },
  { id: 29, cityName: 'Lisbon' },
  { id: 30, cityName: 'Prague' },
  { id: 31, cityName: 'Budapest' },
  { id: 32, cityName: 'Stockholm' },
  { id: 33, cityName: 'St. Petersburg' },
  { id: 34, cityName: 'Brussels' },
  { id: 35, cityName: 'Copenhagen' },
  { id: 36, cityName: 'Seoul' },
  { id: 37, cityName: 'Bangalore' },
  { id: 38, cityName: 'Cape Town' },
  { id: 39, cityName: 'Jakarta' },
  { id: 40, cityName: 'Athens' },
  { id: 41, cityName: 'Dublin' },
  { id: 42, cityName: 'Helsinki' },
  { id: 43, cityName: 'Lima' },
  { id: 44, cityName: 'Lyon' },
  { id: 45, cityName: 'Munich' },
  { id: 46, cityName: 'Oslo' },
  { id: 47, cityName: 'Rio de Janeiro' },
  { id: 48, cityName: 'Zurich' },
  { id: 49, cityName: 'Rotterdam' },
  { id: 50, cityName: 'Warsaw' },
  { id: 51, cityName: 'Tel Aviv' },
  { id: 52, cityName: 'Vancouver' },
  { id: 53, cityName: 'Milan' },
  { id: 54, cityName: 'Venice' },
  { id: 55, cityName: 'Florence' },
  { id: 56, cityName: 'Naples' },
  { id: 57, cityName: 'Verona' },
  { id: 58, cityName: 'Turin' },
  { id: 59, cityName: 'Bologna' },
  { id: 60, cityName: 'Perth' },
  { id: 61, cityName: 'Adelaide' },
  { id: 62, cityName: 'Brisbane' },
  { id: 63, cityName: 'Auckland' },
  { id: 64, cityName: 'Wellington' },
  { id: 65, cityName: 'Christchurch' },
  { id: 66, cityName: 'Fiji' },
  { id: 67, cityName: 'Bora Bora' },
  { id: 68, cityName: 'Bahamas' },
  { id: 69, cityName: 'Maui' },
  { id: 70, cityName: 'Ibiza' },
  { id: 71, cityName: 'Santorini' },
  { id: 72, cityName: 'Crete' },
  { id: 73, cityName: 'Marrakech' },
  { id: 74, cityName: 'Cairo' },
  { id: 75, cityName: 'Casablanca' },
  { id: 76, cityName: 'Johannesburg' },
  { id: 77, cityName: 'Cape Town' },
  { id: 78, cityName: 'Kuala Lumpur' },
  { id: 79, cityName: 'Singapore' },
  { id: 80, cityName: 'Bali' },
  { id: 81, cityName: 'Jakarta' },
  { id: 82, cityName: 'Manila' },
  { id: 83, cityName: 'Bangkok' },
  { id: 84, cityName: 'Chiang Mai' },
  { id: 85, cityName: 'Ho Chi Minh City' },
  { id: 86, cityName: 'Hanoi' },
  { id: 87, cityName: 'Phuket' },
  { id: 88, cityName: 'New Delhi' },
  { id: 89, cityName: 'Mumbai' },
  { id: 90, cityName: 'Kolkata' },
  { id: 91, cityName: 'Bangalore' },
  { id: 92, cityName: 'Chennai' },
  { id: 93, cityName: 'Hyderabad' },
  { id: 94, cityName: 'Pune' },
  { id: 95, cityName: 'Ahmedabad' },
  { id: 96, cityName: 'Surat' },
  { id: 97, cityName: 'Kanpur' },
  { id: 98, cityName: 'Jaipur' },
  { id: 99, cityName: 'Lucknow' },
  { id: 100, cityName: 'Nagoya' },
];

export default citiesNames;
